version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: test-ldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "MultiDBManager Test Org"
      LDAP_DOMAIN: "multidb.local"
      LDAP_BASE_DN: "dc=multidb,dc=local"
      LDAP_ADMIN_PASSWORD: "admin123"
      LDAP_CONFIG_PASSWORD: "config123"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ldap_certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "multidb.local"
    hostname: "ldap-server"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

  ldap-seed:
    image: osixia/openldap:1.5.0
    container_name: ldap-seed
    depends_on:
      - openldap
    command: >
      bash -c "
        sleep 10 &&
        ldapadd -x -D 'cn=admin,dc=multidb,dc=local' -w admin123 -H ldap://openldap:389 -f /tmp/seed.ldif
      "
    volumes:
      - ./config/test-ldap-seed.ldif:/tmp/seed.ldif:ro

volumes:
  ldap_data:
  ldap_config:
  ldap_certs: